{
  "version": 3,
  "sources": [
    "/Users/roymartin/Code/www/roy-martin/app/scripts/modules/index/views/IndexView.js"
  ],
  "names": [],
  "mappings": ";;;;;;;;;;;;;;iBAAc,QAAQ;;;;sBACR,QAAQ;;;;wBACD,UAAU;;;;0BACR,qBAAqB;;;;yBACtB,+BAA+B;;;;qBACnC,gBAAgB;;;;6BAER,8BAA8B;;;;wBACnC,4BAA4B;;;;4BACxB,MAAM;;;;IAElB,SAAS;aAAT,SAAS;8BAAT,SAAS;;;;;;;cAAT,SAAS;;iBAAT,SAAS;;aACN,YAAG;AACX,yCAAe;SAClB;;;aACY,YAAG;AACZ,0BAAc,CAAA;SACjB;;;eACS,oBAAC,MAAM,EAAE;AACf,gBAAI,CAAC,UAAU,GAAG,MAAM,CAAC,UAAU,CAAC;AACpC,gBAAI,CAAC,UAAU,GAAG,MAAM,CAAC,UAAU,CAAC;;AAEpC,gBAAI,CAAC,UAAU,CAAC,aAAa,CAAC;AAC1B,0BAAU,EAAE,IAAI,CAAC,UAAU;aAC9B,CAAC,CAAA;AACF,gBAAI,CAAC,iBAAiB,GAAG,sBAAS,KAAK,CAAC,OAAO,CAAC,YAAY,CAAC,CAAC;;AAE9D,gBAAI,CAAC,iBAAiB,CAAC,EAAE,CAAC,sBAAsB,EAAE,CAAA,YAAW;AACzD,oBAAI,CAAC,gBAAgB,EAAE,CAAC;aAC3B,CAAA,CAAC,IAAI,CAAC,IAAI,CAAC,CAAC,CAAC;AACd,gBAAI,CAAC,iBAAiB,CAAC,EAAE,CAAC,uBAAuB,EAAE,CAAA,YAAW;AAC1D,oBAAI,CAAC,gBAAgB,EAAE,CAAC;aAC3B,CAAA,CAAC,IAAI,CAAC,IAAI,CAAC,CAAC,CAAC;AACd,gBAAI,CAAC,iBAAiB,CAAC,EAAE,CAAC,mBAAmB,EAAE,CAAA,YAAW;AACtD,oBAAI,CAAC,gBAAgB,EAAE,CAAC;aAC3B,CAAA,CAAC,IAAI,CAAC,IAAI,CAAC,CAAC,CAAC;SACjB;;;eACa,0BAAG;;AAEb,2BAAE,eAAe,CAAC,CAAC,IAAI,CAAC,uIAAuI,CAAC,CAAC;AACjK,2BAAE,mBAAmB,CAAC,CAAC,IAAI,CAAC,uDAAuD,CAAC,CAAC;AACrF,2BAAE,qBAAqB,CAAC,CAAC,IAAI,CAAC,EAAE,CAAC,CAAC;AAClC,2BAAE,MAAM,CAAC,CAAC,IAAI,CAAC,OAAO,EAAE,EAAE,CAAC,CAAC,QAAQ,CAAC,WAAW,CAAC,CAAC;SACrD;;;eACe,4BAAG;AACf,gBAAI,CAAC,UAAU,CAAC,gBAAgB,EAAE,CAAC;SACtC;;;eACe,4BAAG;AACf,gBAAI,CAAC,UAAU,CAAC,gBAAgB,EAAE,CAAC;SACtC;;;eACU,uBAAG;AACV,gBAAI,CAAC,UAAU,CAAC,WAAW,EAAE,CAAC;SACjC;;;eACU,uBAAG;;;AAGV,sCAAa,IAAI,CAAC,eAAe,EAAE,GAAE,EAAE;AACnC,iBAAC,EAAE,AAAC,MAAM,CAAC,WAAW,GAAG,CAAC,CAAC,GAAI,IAAI;aACtC,CAAC,CAAC;AACH,sCAAa,IAAI,CAAC,mBAAmB,EAAE,GAAE,EAAE;AACvC,iBAAC,EAAE,MAAM,CAAC,WAAW,GAAG,IAAI;aAC/B,EAAE,CAAC,CAAC,CAAC;SACT;;;eACO,oBAAG;AACP,cAAE,CAAC,MAAM,EAAE,UAAU,CAAC,CAAC;;;AAGvB,2BAAE,IAAI,CAAC,IAAI,CAAC,UAAU,CAAC,KAAK,EAAE,CAAC,CAAC,IAAI,CAAC,CAAA,YAAW;AAC5C,oBAAI,CAAC,WAAW,EAAE,CAAC;AACnB,oBAAI,CAAC,WAAW,EAAE,CAAC;aACtB,CAAA,CAAC,IAAI,CAAC,IAAI,CAAC,CAAC,CAAC;SACjB;;;WA5DQ,SAAS;GAAS,wBAAW,QAAQ;;QAArC,SAAS,GAAT,SAAS",
  "file": "/Users/roymartin/Code/www/roy-martin/app/scripts/modules/index/views/IndexView.js",
  "sourcesContent": [
    "import $ from 'jquery';\nimport _ from 'lodash';\nimport Backbone from 'backbone';\nimport Marionette from 'backbone.marionette';\nimport RadioShim from '../../../vendor/radio.shim.js';\nimport Radio from 'backbone.radio';\n\nimport APICollection from '../collections/APICollection';\nimport template from '../templates/IndexView.hbs';\nimport TimelineLite from 'gsap';\n\nexport class IndexView extends Marionette.ItemView {\n    get template() {\n        return template\n    }\n    get className() {\n        'view-content'\n    }\n    initialize(config) {\n        this.collection = config.collection;\n        this.visualizer = config.visualizer;\n\n        this.visualizer.setCollection({\n            collection: this.collection\n        })\n        this.visualizerChannel = Backbone.Radio.channel('visualizer');\n\n        this.visualizerChannel.on('visualizer:mouseMove', function() {\n            this.getIntersections();\n        }.bind(this));\n        this.visualizerChannel.on('visualizer:touchStart', function() {\n            this.getIntersections();\n        }.bind(this));\n        this.visualizerChannel.on('visualizer:resize', function() {\n            this.updateWindowSize();\n        }.bind(this));\n    }\n    onBeforeRender() {\n        //add title and class\n        $('#header-title').html('<a href=\"http://thoughts.roy-martin.com\" class=\"thoughts\">Thoughts</a> and <a href=\"#experiments\" class=\"experiments\">Experiments</a>');\n        $('#header-sub-title').html('by <a href=\"#about\" class=\"roy-martin\">Roy Martin</a>');\n        $('#header-attribution').html('');\n        $('body').attr('class', '').addClass('indexView');\n    }\n    getIntersections() {\n        this.visualizer.getIntersections();\n    }\n    updateWindowSize() {\n        this.visualizer.updateWindowSize();\n    }\n    renderScene() {\n        this.visualizer.renderScene();\n    }\n    animateHero() {\n        // var t1 = new TimelineLite();\n\n        TimelineLite.from('#header-title', .5, {\n            y: (window.innerHeight * -1) + 'px'\n        });\n        TimelineLite.from('#header-sub-title', .5, {\n            y: window.innerHeight + 'px'\n        }, 0);\n    }\n    onRender() {\n        ga('send', 'pageview');\n\n        // Load the API data before visualizing the results\n        $.when(this.collection.fetch()).then(function() {\n            this.renderScene();\n            this.animateHero();\n        }.bind(this));\n    }\n}\n"
  ],
  "sourceRoot": ""
}